name: Basic Workflow

on:
   workflow_dispatch:
      inputs:
        name:
         description: 'Name' 
         type: string
         required: true



jobs:
  my_job:
   runs-on: ubuntu-18.04
   steps:
     - name: Test
       run: "echo ${{ github.event.inputs.name }}"
        
         