name: CI pipe run and build

on:
  push:
    branches:
      - "main"

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: List of repo
        run:  list ${{ github.workspace }}
      - name: Setup python version 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run:
           pip install -r requirements.txt    